### ISSUE TITLE
Добавить модель для роли

### ISSUE THREAD

**Issue by Vv-vfx** [veroneoriginal/english_shool#10]
**Если эта feature связана с какой то проблемой, пожалуйста опишите её**
Нет модели для ролей

**Опишите решение, которое вы хотите видеть**
1. Создать модель для ролей. Может быть зарегистрированный, студент, преподаватель
2. Добавить тесты для модели
3. Связать модель с моделью User. Пользователь может принадлежать к одной или нескольким ролям.
4. Добавить тесты

**Опишите альтернативные решения**
Подумать, стоит ли заводить для этого отдельную модель или можно воспользоваться CHOISE

**Дополнительная информация**
Про choise можно спросить у GPT

**Comment by veroneoriginal** [comment]
на текущий момент воспользовалась Choise, но тогда роль у usera может быть только 1.
